Vagrant.configure("2") do |config|
  config.vm.synced_folder "%DOMAINPATH", "/vagrant"
  config.vm.define :%VM do |node|
    node.vm.box = "%IMG"
    node.vm.hostname = "%VM"
    node.vm.provision "shell", run: "always", inline: "/bin/sh /vagrant/sync/%SCRIPT"
    node.vm.provider :libvirt do |domain|
      domain.management_network_address = "192.168.122.0/24"
      domain.management_network_name = "default"
      domain.management_network_mode = "nat"
      domain.management_network_mac = "%MAC"
      domain.memory = %MEM
      domain.cpus = %CPU
      domain.machine_virtual_size = %DISK
      domain.nested = true
    end
  end  
end

