---
- name: mesos-master-tasks
  become: true
  import_tasks: mesos-master-tasks.yml

- name: mesos-install-zk
  become: true
  import_tasks: mesos-install-zk.yml

- name: mesos-install-marathon
  become: true
  import_tasks: mesos-install-marathon.yml

- name: enable Master services
  become: true
  systemd: state=restarted enabled=yes name={{ item }}
  with_items:
    - '{{ MASTERSERVICES }}'