---
- name: Install Kubernetes
  hosts: KUBE
  gather_facts: true
  roles:
    - role: kube-install

- name: Kubernetes Masters
  hosts: KUBEMASTERS
  gather_facts: false
  roles:
    - role: kube-master

- name: Kubernetes Workers
  hosts: KUBEWORKERS
  gather_facts: false
  roles:
    - role: kube-worker
